### PR TITLE
release-2023-03-30

### PR DESCRIPTION
**Pull request by edu-stx**
> [Download the latest build](https://github.com/hirosystems/desktop-wallet/actions/runs/4678753620)

Commit body

### CODE REVIEW

**Comment by markmhx** [comment]
@edu-stx mind linking the relevant issues here on the right and moving them to the review column? 

Screenshot 2023-03-30 at 13 46 01

**Comment by markmhx** [comment]
Yea I'm not sure about https://github.com/hirosystems/desktop-wallet/issues/1164 but maybe @314159265359879 has insight into whether we can tackle it wallet-side

**Comment by 314159265359879** [comment]
If a wallet has 1000.58928 STX and 1000 STX was stacking.

Sending anything over .51 STX will pend forever. But if they send the STX that were never locked they can work around it. 
They can send a small amount 0.000001 STX to any address (burn address for example) and that will resolve the "lock". 

In the three cased I handles yesterday the desktop-wallet-user had already send a transaction, they would have to replace the transaction so it gets processed first (first nonce that can be processed and a fee that is higher then that of the transaction already pending with that nonce, 0.072001 STX). 

A more general option to (request to) delete/cancel a transaction would be helpful as proposed here: https://github.com/hirosystems/stacks-wallet-web/issues/3406

Perhaps a tall order for the desktop wallet?

**Review by friedger — CHANGES_REQUESTED** [review]
The stacks dependencies (in particular @stacks/stacking) need to be updated to 6.5+
Otherwise #733 still fails

**Pull request merged**
